import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image'
import imgShop from '../public/img/shop-icon.jpg';
import imgUser from '../public/img/user-icon.jpg';
import BasicMenu from './BasicMenu';

const MainContainer = ({ children }) => {

  const [user, setUser] = useState('');
  const { login } = user;

  useEffect(() => {
    const obj = JSON.parse(localStorage.getItem('user'))
    setUser(obj || '');
  }, []);
  const username = login?.split('@')[0];
  const listmenu = username
    ? [
      { id: 0, url: '/orders', name: 'My orders' },
      { id: 1, url: '/exit', name: 'Log Out' }
    ]
    : [
      { id: 0, url: '/login', name: 'Log In' },
      { id: 1, url: '/register', name: 'Register' },
    ]
  return (
    <>
      <Head>
        <title>MarketPlace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <div className='container__header'>
          <div className="header__title">
            <h1>
              MarketPlace
            </h1>
          </div>
          <div className="header__horizontal">
          </div>
          <div className="header__nav">
            <div className='nav-container'></div>
            <div className="menu__list nav-container">
              <Link href="/">
                <a >Home</a>
              </Link>
              <Link href="/shop">
                <a>Магазин</a>
              </Link>
            </div>
            <div className="account__container nav-container">
              <div className="account__icon-user account">
                <Image
                  src={imgUser}
                  alt="Picture of the author"
                />
              </div>
              <div className="account__authorize account">
                {username
                  ? <BasicMenu setUser={setUser} user={user} title={username} listmenu={listmenu} />
                  : <BasicMenu title='Log In' listmenu={listmenu} />

                }
              </div>
              {username
                ? <div className="account__icon-shop account">
                  <Image
                    src={imgShop}
                    alt="Picture of the author"
                  />
                </div>
                : null
              }

            </div>
          </div>
        </div>
        <>
          {children}
        </>
      </div>
    </>
  )
}

export default MainContainer;
